### ISSUE TITLE
UX report

### ISSUE THREAD

**Issue by AgricultureAlex** [jhuopensource/semesterly#1039]
### Describe the Bug

Can you trade the icons for "new timetable" and "custom event"
Love the app a ton 🙏 overall I love the interface and how it looks. But I must've clicked on this "new timetable" thing at least 30 times every semester, which I don't think is meant to happen

### How can we reproduce the problem?

See image

### Expected Behavior

See image

### OS Version

None

### Additional Information

<img width="505" alt="Capture d’écran 2023-10-03 à 19 48 21" src="https://github.com/jhuopensource/semesterly/assets/107017061/ce36d27a-f6ce-4f20-a40d-38261547d435">

### Code of Conduct

- [X] I agree to follow Semester.ly's Code of Conduct

**Comment by AgricultureAlex** [comment]
I meant to delete the note on the left. That one makes sense once you use it once

**Comment by JiaqiWang18** [comment]
thanks for this great suggestion! I will disucuss this with the rest of Semester.ly development team.
