### ISSUE TITLE
Get and Store Student SIS Data

### ISSUE THREAD

**Issue by miaboloix** [jhuopensource/semesterly#128]
In order to create an advising dashboard with an official schedule, we need the be able to see a student's official semester data.

This will involve:
- Designing and API with @alihacks 
- Creating a few mock json files for testing/creating features with this data

**Comment by Boccca2014** [comment]
My work thusfar: [link here](https://docs.google.com/document/d/1-Yjl5-iLrtbKXYPUz0HkrrR-UjhWEg7FdkcgmDcsT7I/edit?usp=sharing)
I'll let you and Ali know when I'm done.

**Comment by Boccca2014** [comment]
Added some mock JSONs in the pull request above. And updated API formatting also noted in the Google Doc.

**Comment by Boccca2014** [comment]
Updated JSON format into single JSON file.

**Comment by Boccca2014** [comment]
We want to test that the following sequences of authentication work:
- [ ] v1.7.0 PyJWT (Understand PyJWT and JWT Tokens)
- [ ] urls.py add url ^→ look at gcal
- [ ] Create views.py function
- [ ] link user and advisor

**Comment by miaboloix** [comment]
Can you also draw a diagram similar to the one I sent & attach it here? I think the visual is helpful :)

**Comment by Boccca2014** [comment]
Student SIS API Diagram -> [LINK](https://drive.google.com/file/d/1qyJ2s9pxmsnwzPq1h9jKTDpRXdAFesqi/view?usp=sharing)

**Comment by Boccca2014** [comment]
- [ ] Create thorough test.py
- [ ] Add all views
- [ ] Confirm Advising Model is valid
- [ ] Add comments for all files
