### ISSUE TITLE
Create initial Advising Dashboard frontend components

### ISSUE THREAD

**Issue by miaboloix** [jhuopensource/semesterly#151]

**Comment by Boccca2014** [comment]
- [ ] add a border to courses
- [ ] + button for profs modal on right-hand side
- [ ] make modal for profs
- [ ] make the upper-left-hand logo not green
- [ ] add an empty line for forum box

**Comment by Boccca2014** [comment]
- [ ] Modify CSS for invite advisors modal
- [ ] Create endpoints connection (for forum)
- [ ] Improve lefthand logo with improved CSS
