### ISSUE TITLE
Revamp Advanced Search feature

### ISSUE THREAD

**Issue by miaboloix** [jhuopensource/semesterly#202]
The typical Semester.ly user at JHU searches for some or all of their courses using SIS's Advanced Search feature. Typically, Semester.ly comes in when students are decided which courses (of those found through SIS) will fit together in a nice schedule. This feature aims to completely eliminate the need for users to use SIS's Advanced Search feature. We want Semester.ly's search to be just as good if not BETTER than SIS's search.

Should adjust the UI/UX as well the backend for advanced search feature. The reviews section is outdated and needs to be replaced with a sufficient, sustainable API.

**Comment by JJamesWWang** [comment]
Large feature requests like this are being moved to the Project Interests in Projects.
