### ISSUE TITLE
Update course reviews/evaluations with more recent data 

### ISSUE THREAD

**Issue by miaboloix** [jhuopensource/semesterly#206]
Depending on what this entails - it may be a semester-long project?

At the moment, the course review data on Semester.ly is really outdated (think 2014 and 2015 data… yikes!). With this project, your task would be to figure out how the original course review data was ingested and processed on Semester.ly, and either apply that process to more current course review data or figure out a better way to sustainably ingest the new data

**Comment by JJamesWWang** [comment]
Large feature requests like this are being moved to the Project Interests in Projects.
