### ISSUE TITLE
Migrate to Python 3

### ISSUE THREAD

**Issue by miaboloix** [jhuopensource/semesterly#207]
As of Jan 2020, Python 2.7 reached its EOL as noted [here](https://devguide.python.org/devcycle/#end-of-life-branches).

It's crucial to upgrade to the latest stable release of Python3.

Previous Attempts to upgrade to Python 3
[Best reference](https://github.com/noahpresler/semesterly/pull/1154) (since it was resolved at ITCR)

https://github.com/noahpresler/semesterly/pull/1021
https://github.com/noahpresler/semesterly/pull/1014
https://github.com/noahpresler/semesterly/pull/1033

**Comment by sGerli** [comment]
I'm currently using a newer version of noahpresler#1154 on my instance, I made that PR in there as a mistake, as I meant to make it on my fork. I think that after merging that PR i had to make a few more fixes for problems that I discovered later.

Note:  I also upgraded Django to 2.2. My fork also has a few adaptations, like having saturday and sunday, static html text changes, and other minor modifications that were required to make it work with my university.

If you want you can take a look at all that I did and take what works for you.

**Comment by Boccca2014** [comment]
@sGerli Thanks! I've been looking over your PR for the past day trying to sort this out incrementally. I realized I should go back to the original branch you merged then implement any changes you added after because some of our university's timetable and other info needs to be retained. Hopefully, I can figure this out soon.

**Comment by Boccca2014** [comment]
@sGerli I forgot to ask if you're interested in promoting your school's version of Semester.ly on our original site. For instance, I could put it in the section of the page indicated below. Feel free to msg back here, join our [Discord](https://discord.gg/txYbphsAV7) to discuss further, or email me at contact@semester.ly.

<img width="407" alt="Screen Shot 2021-06-21 at 7 32 05 AM" src="https://user-images.githubusercontent.com/14218992/122755289-c8a7cc00-d262-11eb-9dbf-ca19ea917290.png">

**Comment by sGerli** [comment]
Great, already joined your Discord.
