### ISSUE TITLE
Create a feature request tool 

### ISSUE THREAD

**Issue by miaboloix** [jhuopensource/semesterly#210]
As it stands, there isn’t a simple way for users to suggest new features they would like for Semester.ly. Every once in a while, the team sends out surveys and that is how we currently get feedback from users. However, something that would be really cool is a place on the Semester.ly homepage for users to submit feature requests or suggestions for improvement!

**Comment by JJamesWWang** [comment]
Large feature requests like this are being moved to the Project Interests in Projects.
