### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by Boccca2014** [jhuopensource/semesterly#329]
Could be done with Bootstrap using a non-native library, like [Bootswatch](https://bootswatch.com/darkly/), but we could use [TailwindCSS](https://tailwindcss.com/docs/dark-mode) or [Chakra-UI](https://chakra-ui.com/docs/features/color-mode) to modernize the UI overall during this conversion.

**Comment by JJamesWWang** [comment]
Large feature requests like this are being moved to the Project Interests in Projects.
