### ISSUE TITLE
Prepend Share Links in Advanced Search

### ISSUE THREAD

**Issue by Boccca2014** [jhuopensource/semesterly#345]
**Issue**
The share links are invalid.
<img width="520" alt="Screen Shot 2021-07-07 at 1 16 00 PM" src="https://user-images.githubusercontent.com/14218992/124802067-8ef2e880-df25-11eb-82dd-7c2dc75e8bd3.png">
Linked with #202 

**Possible Solution**
Check `course_modal_body.jsx`
Need to prepend with https://jhu.semester.ly (i.e. https://jhu.semester.ly/course/EN.600.315/Fall/2021). Note that this only happens in advanced search, NOT when you view the course directly
i.e. 
<img width="1193" alt="Screen Shot 2021-07-07 at 1 19 13 PM" src="https://user-images.githubusercontent.com/14218992/124802404-ef822580-df25-11eb-9043-22593d483eac.png">

**Comment by yesterd3v** [comment]
Resolve partially, corrected when viewing course alone but not in "Advanced Search" view.

**Comment by yesterd3v** [comment]
Resolved
