### ISSUE TITLE
Fix CSS of Navbar (must be dynamic)

### ISSUE THREAD

**Issue by Boccca2014** [jhuopensource/semesterly#368]
### Describe the Bug

Navbar CSS is invalid with smaller widths.

### How can we reproduce the problem?

N/A

### Expected Behavior

Navbar should flex dynamically with the viewport.

### OS Version

MacOS

### Which browsers are you seeing the problem on?

Chrome, Other

### Additional Information

<img width="1175" alt="Screen Shot 2021-08-30 at 3 47 28 PM" src="https://user-images.githubusercontent.com/14218992/131396360-e66da973-988d-410c-883e-bd144deffe22.png">

### Code of Conduct

- [X] I agree to follow Semester.ly's Code of Conduct

**Comment by JJamesWWang** [comment]
@Boccca2014 can this be closed?
