### ISSUE TITLE
Automate New Semesters' Parser

### ISSUE THREAD

**Issue by yesterd3v** [jhuopensource/semesterly#411]
### Describe the Bug

At the moment, we manually have to add a new section for the next semester at some point during the current one.
It would be ideal if this could be automated, such that a specific line or trigger could automatically restart the parser without any developer creating a new PR.

Reference for manual update -> #410 #415 

We should almost automate choosing class year or let the user decide (perhaps simply pull from SIS instead?)
This can be found here -> static/js/redux/ui/modals/user_settings_modal.jsx

### How can we reproduce the problem?

N/A

### Expected Behavior

No longer need to create new PRs to parse data for new semesters.

### Code of Conduct

- [X] I agree to follow Semester.ly's Code of Conduct

**Comment by JJamesWWang** [comment]
Large feature requests like this are being moved to the Project Interests in Projects.
