### ISSUE TITLE
Refactor Drag and Drop to Functional Component

### ISSUE THREAD

**Issue by alexcjwei** [jhuopensource/semesterly#719]
We want to refactor our drag-and-drop components into hooks. 
Our current drag-and-droppable components are:
* Cell (calendar_cell.jsx)
* Slot (slot.jsx)
* CustomSlot (custom_slot_.tsx)
We use the [react-dnd ](https://react-dnd.github.io/react-dnd/examples/sortable/cancel-on-drop-outside) npm package.

The main reason for refactoring to functional is because the react-dnd decorator allows us to call function whenever dragging stops with `end` as described in the [react-dnd docs](https://react-dnd.github.io/react-dnd/docs/api/use-drag)

**Comment by JJamesWWang** [comment]
This is optional now that we've fixed the original dnd issue; feel free to continue or close
