### ISSUE TITLE
Course mIssing

### ISSUE THREAD

**Issue by abhishekdas234** [jhuopensource/semesterly#851]
### Contact Details

NA

### Is your feature request related to a problem? Please describe.

Yes

### Describe the solution you'd like.

Biophysical Chemistry course is not on here

### Describe alternatives you've considered

Adding to schedule myself

### Additional Information

NA

### Code of Conduct

- [X] I agree to follow Semester.ly's Code of Conduct

**Comment by JJamesWWang** [comment]
@abhishekdas234 Hi, could you let me know what the course code is for the course? (AS.\_\_.\_\_)

**Comment by JJamesWWang** [comment]
We just tried searching for Biophysical Chemistry and were able to find it.

![image](https://user-images.githubusercontent.com/27985363/199620005-ab826401-d637-4236-81c7-a2e0456590e9.png)

We're not sure why this happened. Next time, try to search with the course code as well and see if it pops up.
